name: Snapcraft

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
    - id: run-help
      run: |
        sudo snap install --dangerous ${{ steps.build.outputs.snap }}
        charmhub-lp-tool --help
    - id: publish
      if: github.ref == 'refs/heads/main'
      uses: snapcore/action-publish@v1
      env:
        # See: https://github.com/snapcore/action-publish#store-login
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
